# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
- package-ecosystem: "github-actions" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"

- package-ecosystem: "uv"
  directory: "/"
  schedule:
    interval: "weekly" # You can change this to "daily" or "monthly"
  # Optional: Groups can help batch updates into a single PR
  groups:
    python-packages:
      patterns:
        - "*"